from __future__ import annotations

from .base import Base, get_engine, get_session_factory, init_db, new_id
from .draft import CandidateDraftRecord, ChapterDraft, ChapterReview
from .canon_quality import (
    ArtifactCollectionLedgerRow,
    CanonAdmissionRunRow,
    CanonQualitySignalRow,
    ChapterBodyMetricRow,
    CharacterStateTransitionRow,
    CountdownLedgerRow,
    RevealRegistryEntryRow,
    StoryObligationRow,
)
from .entity import Entity, EntityAlias, EntityState, RelationEdge
from .event import CanonEvent, EventEntityLink
from .genesis import BookGenesisRevision, PromptTrace
from .governance import BandCheckpoint, DecisionEvent, NarrativeConstraint
from .observability import PerformanceSpan
from .narrative_obligation import FuturePlanAuditRunRow, NarrativeObligationRow, NarrativePlanPatchRow
from .phase import (
    ArcEnvelope,
    ArcEnvelopeAnalysis,
    ArcStructureDraft,
    BandExperiencePlan,
    ChapterRewriteAttempt,
    ProjectReplanEvent,
    ProjectStageAnalysis,
    ProvisionalChapterLedger,
    ProvisionalBandExecution,
    ProvisionalPromotionRecord,
    WorldProjectionDeltaRow,
)
from .phase4 import NPCIntentSnapshot, WorldSimulationTurn
from .progression import ProjectProgressionRule
from .publisher import (
    CommentSignalCandidate,
    FeedbackActionRecord,
    PublisherBrowserSession,
    PublisherBrowserSessionEntry,
    PublisherChapterBinding,
    PublisherCommentSyncJob,
    PublisherConnectionState,
    PublisherCoverAsset,
    PublisherExtensionClient,
    PublisherExtensionPlatformState,
    PublisherMilestone,
    PublisherRawComment,
    PublisherUploadJob,
    PublisherWorkBinding,
    ReaderScaleSnapshot,
    SignalWindowAggregate,
)
from .project import ArcPlanVersion, ChapterPlan, Project
from .subworld import SubWorld, SubWorldRosterItem
from .task import GenerationTask
from .thread import PlotThread, PlotThreadBeat
from .timeline import ChapterTimeline, StoryTimePoint
from forwin.map.models import MapGenerationRunRow, MapRegionEdgeRow, MapRegionRow
from .world_model import (
    WorldEditProposalRow,
    WorldModelCompileRunRow,
    WorldModelConflictRow,
    WorldModelLinkRow,
    WorldModelPageRow,
    WorldModelSnapshotRow,
)
from .world_v4 import (
    ArcWorldContractRow,
    BandWorldContractRow,
    BeliefRow,
    ChapterWorldDeltaIntentRow,
    CognitionSnapshotRow,
    KnowledgeGapRow,
    KnowledgeUpdateEventRow,
    ReaderExperienceDeltaRow,
    RevealEventRow,
    ScenarioRehearsalRunRow,
    ScenarioPlanPatchRow,
    WorldCompileRunV4Row,
    WorldDeltaRow,
    WorldLineRow,
    WorldModelSnapshotV4Row,
)
from .book_state import (
    BookCognitionSnapshotRow,
    CharacterIdentityMapRow,
    BookReaderExperienceDeltaRow,
    BookReaderPromiseRow,
    CognitionOverlayPatchRow,
    CognitionOverlayRow,
    FactNodeRow,
    GraphDeltaPatchRow,
    GraphDeltaRow,
    MapEdgeRow,
    MapNodeRow,
    MapSnapshotRow,
    NarrativeEdgeRow,
    NarrativeNodeRow,
    WorldEdgeRow,
    WorldNodeRow,
    WorldNodeStateRow,
    WorldSnapshotRow,
)

__all__ = [
    "Base",
    "get_engine",
    "get_session_factory",
    "init_db",
    "new_id",
    # project
    "Project",
    "ArcPlanVersion",
    "ChapterPlan",
    "ProjectProgressionRule",
    "GenerationTask",
    "SubWorld",
    "SubWorldRosterItem",
    # entity
    "Entity",
    "EntityAlias",
    "EntityState",
    "RelationEdge",
    # event
    "CanonEvent",
    "EventEntityLink",
    "BookGenesisRevision",
    "PromptTrace",
    "BandCheckpoint",
    "NarrativeConstraint",
    "DecisionEvent",
    "PerformanceSpan",
    "NarrativeObligationRow",
    "NarrativePlanPatchRow",
    "FuturePlanAuditRunRow",
    "ProjectStageAnalysis",
    "ProjectReplanEvent",
    "ArcEnvelope",
    "ArcStructureDraft",
    "ArcEnvelopeAnalysis",
    "BandExperiencePlan",
    "ChapterRewriteAttempt",
    "ProvisionalChapterLedger",
    "ProvisionalBandExecution",
    "ProvisionalPromotionRecord",
    "WorldProjectionDeltaRow",
    "NPCIntentSnapshot",
    "WorldSimulationTurn",
    # thread
    "PlotThread",
    "PlotThreadBeat",
    # timeline
    "StoryTimePoint",
    "ChapterTimeline",
    # draft
    "ChapterDraft",
    "ChapterReview",
    "CandidateDraftRecord",
    "ArtifactCollectionLedgerRow",
    "CanonAdmissionRunRow",
    "CanonQualitySignalRow",
    "ChapterBodyMetricRow",
    "CharacterStateTransitionRow",
    "CountdownLedgerRow",
    "RevealRegistryEntryRow",
    "StoryObligationRow",
    "WorldModelSnapshotRow",
    "WorldModelPageRow",
    "WorldModelLinkRow",
    "WorldEditProposalRow",
    "WorldModelConflictRow",
    "WorldModelCompileRunRow",
    # publisher
    "CommentSignalCandidate",
    "FeedbackActionRecord",
    "PublisherExtensionClient",
    "PublisherExtensionPlatformState",
    "PublisherConnectionState",
    "PublisherBrowserSession",
    "PublisherBrowserSessionEntry",
    "PublisherUploadJob",
    "PublisherWorkBinding",
    "PublisherChapterBinding",
    "PublisherCoverAsset",
    "PublisherMilestone",
    "PublisherCommentSyncJob",
    "PublisherRawComment",
    "ReaderScaleSnapshot",
    "SignalWindowAggregate",
    # world v4
    "WorldLineRow",
    "WorldDeltaRow",
    "BeliefRow",
    "CognitionSnapshotRow",
    "KnowledgeGapRow",
    "RevealEventRow",
    "KnowledgeUpdateEventRow",
    "ReaderExperienceDeltaRow",
    "ScenarioRehearsalRunRow",
    "ScenarioPlanPatchRow",
    "WorldModelSnapshotV4Row",
    "WorldCompileRunV4Row",
    "ArcWorldContractRow",
    "BandWorldContractRow",
    "ChapterWorldDeltaIntentRow",
    # final book state
    "WorldNodeRow",
    "WorldNodeStateRow",
    "CharacterIdentityMapRow",
    "WorldEdgeRow",
    "FactNodeRow",
    "MapNodeRow",
    "MapEdgeRow",
    "MapRegionRow",
    "MapRegionEdgeRow",
    "MapGenerationRunRow",
    "GraphDeltaRow",
    "GraphDeltaPatchRow",
    "CognitionOverlayRow",
    "CognitionOverlayPatchRow",
    "WorldSnapshotRow",
    "MapSnapshotRow",
    "BookCognitionSnapshotRow",
    "BookReaderPromiseRow",
    "BookReaderExperienceDeltaRow",
    "NarrativeNodeRow",
    "NarrativeEdgeRow",
]
