from __future__ import annotations

import copy
from typing import Any


_DEFAULT_MINIMUM_WORLD_SYSTEM: dict[str, Any] = {
    "institution": {
        "legitimacy_source": "",
        "top_public_title": "",
        "actual_power_holder": "",
        "hierarchy_ladder_3_to_5_levels": [],
        "succession_or_appointment": "",
        "enforcement_method": "",
        "internal_conflict": "",
    },
    "economy": {
        "scarce_resource": "",
        "controller": "",
        "currency": "",
        "calendar_or_cycle": "",
        "key_technology": "",
        "black_market": "",
        "crisis_trigger": "",
    },
    "narrative": {
        "who_is_restricted": "",
        "who_is_tempted": "",
        "who_gets_hurt": "",
        "who_profits": "",
        "what_scene_can_explode": "",
    },
}

_DEFAULT_MINIMUM_EXTENSION_PACK: dict[str, Any] = {
    "daily_life": {
        "staple_food": "",
        "status_clothing": "",
        "greeting": "",
        "insult": "",
        "funeral_or_marriage_custom": "",
    },
    "belief_mythos": {
        "greatest_sin": "",
        "sacred_taboo": "",
        "public_myth": "",
        "hidden_truth": "",
    },
    "information": {
        "fastest_message_channel": "",
        "who_controls_records": "",
        "common_false_belief": "",
    },
    "ecology": {
        "main_environment": "",
        "greatest_natural_danger": "",
        "valuable_species_or_material": "",
    },
    "aesthetic": {
        "three_tone_words": [],
        "recurring_image": "",
        "signature_weather_or_sound": "",
    },
    "secrets": {
        "public_belief": "",
        "hidden_truth": "",
        "reveal_stage": "",
    },
    "value_conflict": {
        "issue": "",
        "side_a": "",
        "side_b": "",
        "protagonist_pressure": "",
    },
    "story_interface": {
        "scene": "",
        "choice": "",
        "cost": "",
        "payoff": "",
    },
}

_DEFAULT_WORLD_EXTENSIONS: dict[str, Any] = {
    "daily_life_profiles": [],
    "belief_mythos_profiles": [],
    "information_profiles": [],
    "ecology_profiles": [],
    "aesthetic_profiles": [],
    "secrets_codex": [],
    "value_conflicts": [],
    "story_interfaces": [],
}

_TITLE_LEXICON_PACK: dict[str, Any] = {
    "christian_like": {
        "ruler": ["教皇", "宗主教", "圣座", "首席牧者"],
        "council": ["枢机团", "主教会议", "神学公会"],
        "regional": ["大主教", "主教", "教区长"],
        "local": ["司铎", "神父", "牧师", "执事"],
        "members": ["修士", "修女", "信众", "朝圣者"],
        "court": ["宗教裁判所", "圣典署", "赦罪院", "圣物库"],
        "taboo": ["异端", "亵渎", "破门", "绝罚"],
    },
    "sino_imperial": {
        "ruler": ["皇帝", "天子", "王", "圣上"],
        "center": ["丞相", "首辅", "中书", "尚书台", "军机处"],
        "departments": ["吏部", "户部", "礼部", "兵部", "刑部", "工部", "御史台"],
        "regional": ["总督", "巡抚", "刺史", "太守", "知府"],
        "local": ["县令", "县丞", "主簿", "里正", "保长", "族长"],
        "members": ["士人", "庶民", "佃户", "工匠", "商贾", "贱籍"],
        "taboo": ["谋逆", "僭越", "乱伦", "失礼", "欺君"],
    },
    "xianxia_sect": {
        "ruler": ["宗主", "掌门", "山主", "宫主"],
        "council": ["太上长老", "护法长老", "宗老会"],
        "departments": ["戒律堂", "丹房", "器阁", "传功堂", "外务堂", "藏经楼"],
        "regional": ["峰主", "堂主", "分舵主", "客卿长老"],
        "members": ["亲传", "真传", "内门", "外门", "杂役", "散修"],
        "taboo": ["欺师灭祖", "私传禁术", "叛宗", "入魔"],
    },
    "clan_family": {
        "ruler": ["家主", "宗主", "族长"],
        "council": ["宗老会", "叔伯会", "祠堂议事"],
        "departments": ["账房", "家兵营", "婚事房", "祠堂", "田庄管事"],
        "regional": ["房头", "庄头", "掌柜", "管事"],
        "members": ["嫡支", "庶支", "外戚", "家生子", "门客", "奴仆"],
        "taboo": ["败坏门风", "断香火", "私奔", "侵吞祖产"],
    },
    "nomad_tribal": {
        "ruler": ["大汗", "可汗", "大酋长", "王帐之主"],
        "council": ["王帐贵族", "长老会", "巫祝会", "部落大会"],
        "regional": ["部落首领", "台吉", "氏族长", "千夫长"],
        "local": ["百夫长", "猎队长", "牧队长", "营帐主"],
        "members": ["战士", "牧户", "俘虏", "工匠", "祭司"],
        "taboo": ["背誓", "盗马", "亵渎祖灵", "破坏水源"],
    },
    "merchant_guild": {
        "ruler": ["会长", "执政商人", "大掌柜", "董事长"],
        "council": ["商盟议会", "大股东会", "长老会"],
        "departments": ["账房", "船队", "仓储", "票号", "工坊", "护卫队"],
        "regional": ["分会长", "船队长", "行首", "区域总监"],
        "members": ["掌柜", "经纪人", "学徒", "雇工", "搬运工"],
        "taboo": ["坏账", "失信", "假货", "私开航线", "盗印票据"],
    },
    "corporate_cyber": {
        "ruler": ["董事会主席", "CEO", "创始人", "控股人格"],
        "council": ["董事会", "风险委员会", "算法治理组"],
        "departments": ["法务", "安保", "数据", "生物研发", "市场", "资产回收"],
        "regional": ["区域总裁", "项目总监", "站点经理"],
        "members": ["正式员工", "合同工", "外包工", "数据债务人", "合成体"],
        "taboo": ["泄露协议", "盗取算力", "侵犯专利", "破坏品牌"],
    },
    "military_junta": {
        "ruler": ["最高统帅", "大元帅", "军政府主席"],
        "council": ["参谋本部", "将军团", "军事委员会"],
        "regional": ["战区司令", "军团长", "舰队司令"],
        "local": ["团长", "营长", "连长", "队长"],
        "members": ["士兵", "民兵", "军属", "后勤工", "俘虏"],
        "taboo": ["叛逃", "抗命", "泄密", "临阵脱逃", "破坏军纪"],
    },
    "underworld": {
        "ruler": ["龙头", "隐主", "老板", "影王"],
        "council": ["堂主会", "红棍会", "账本会"],
        "regional": ["堂主", "区域头目", "船头", "档口主"],
        "local": ["香主", "组长", "打手头", "中间人"],
        "members": ["马仔", "线人", "走私客", "杀手", "外围"],
        "taboo": ["出卖兄弟", "黑吃黑", "破坏规矩", "私吞货款"],
    },
}

_VALUE_CONFLICT_PROMPTS: list[dict[str, Any]] = [
    {"issue": "血统是否决定统治权", "side_a": "血统保证秩序", "side_b": "能力和功绩才配拥有权力"},
    {"issue": "为了多数人能否牺牲少数人", "side_a": "必须牺牲，否则全体灭亡", "side_b": "一旦允许牺牲，权力会不断扩大牺牲范围"},
    {"issue": "复仇是否等于正义", "side_a": "没有复仇，受害者永远无法被看见", "side_b": "复仇只会延续暴力链条"},
    {"issue": "禁术或危险技术是否应该被公开", "side_a": "公开会毁灭社会", "side_b": "垄断知识才是真正危险"},
    {"issue": "秩序是否高于自由", "side_a": "没有秩序，弱者先死", "side_b": "没有自由，秩序只是体面奴役"},
    {"issue": "传统是否应该被保留", "side_a": "传统保护共同体记忆", "side_b": "传统也保护压迫者利益"},
    {"issue": "人是否可以被改造", "side_a": "改造能消除疾病、弱点和犯罪", "side_b": "改造会消灭人的不可替代性"},
    {"issue": "真相是否必须公开", "side_a": "谎言上的和平不可持续", "side_b": "有些真相会让社会立刻崩溃"},
]

_TEMPLATE_LIBRARIES: dict[str, Any] = {
    "institution_templates": {
        "institution_profile_template": {
            "id": "",
            "name": "",
            "scope_ref": {"type": "", "id": ""},
            "template_type": "",
            "title_lexicon_id": "",
            "one_sentence_summary": "",
            "legitimacy_source": [],
            "authority_model": {
                "type": "",
                "actual_power_holder": "",
                "public_power_holder": "",
                "gap_between_public_and_actual": "",
            },
            "hierarchy_ladder": [],
            "offices": [],
            "law_and_order": {
                "law_source": "",
                "enforcement": "",
                "punishment_style": "",
                "loopholes": "",
            },
            "succession": {
                "normal_method": "",
                "crisis_method": "",
                "common_disputes": "",
                "forbidden_claimants": "",
            },
            "internal_conflicts": [],
            "story_interfaces": {
                "generates_conflict": "",
                "forces_character_choice": "",
                "creates_cost": "",
                "hides_secret": "",
                "usable_scenes": [],
            },
        },
        "rank_card_template": {
            "level": 1,
            "title": "",
            "alternate_titles": [],
            "belongs_to": {"institution_profile_id": ""},
            "authority_scope": {
                "territory": "",
                "people": "",
                "resources": "",
                "law": "",
                "military": "",
                "ritual": "",
                "information": "",
            },
            "appointment": {
                "method": "",
                "appointer": "",
                "eligibility": "",
                "term_length": "",
                "removal_method": "",
            },
            "duties": {"public_duties": "", "hidden_duties": "", "emergency_duties": ""},
            "privileges": {
                "economic": "",
                "legal": "",
                "symbolic": "",
                "sexual_marriage": "",
                "travel": "",
                "speech": "",
            },
            "constraints": {
                "taboos": "",
                "vows": "",
                "surveillance": "",
                "political_limits": "",
                "ritual_limits": "",
            },
            "symbols": {
                "clothing": "",
                "token": "",
                "title_style": "",
                "greeting_style": "",
                "seal_or_emblem": "",
            },
            "narrative_use": {
                "typical_scene": "",
                "common_abuse": "",
                "likely_enemy": "",
                "likely_ally": "",
                "secret_they_may_know": "",
            },
        },
        "hierarchy_templates": [
            {"id": "sacred_three_layer", "name": "三层神权模板", "common_conflicts": ["中央教义 vs 地方习俗", "神权 vs 王权", "纯洁派 vs 世俗派", "真神迹 vs 伪神迹"]},
            {"id": "imperial_five_layer", "name": "五层帝国官僚模板", "common_conflicts": ["皇权 vs 相权", "中央法令 vs 地方习俗", "文官 vs 武将", "士族门第 vs 寒门新贵"]},
            {"id": "feudal_four_layer", "name": "四层封建领主模板", "common_conflicts": ["王权虚弱，诸侯坐大", "继承婚姻引发领地战争", "领主保护义务 vs 农民负担"]},
            {"id": "sect_academy_five_layer", "name": "五层宗门学院模板", "common_conflicts": ["天赋血统 vs 后天努力", "掌门系 vs 长老系", "资源倾斜导致内斗"]},
            {"id": "tribal_four_layer", "name": "四层部落联盟模板", "common_conflicts": ["联盟统一 vs 部落自治", "战利品分配不公", "血仇压倒政治理性"]},
            {"id": "guild_corporate_five_layer", "name": "五层行会公司模板", "common_conflicts": ["利润 vs 道德", "总部 vs 地方分会", "垄断技术 vs 开放市场"]},
            {"id": "military_six_layer", "name": "六层军政军团模板", "common_conflicts": ["前线真实情况 vs 后方战报", "军令 vs 良知", "后勤短缺引发失败"]},
            {"id": "secret_society_five_layer", "name": "五层秘密结社模板", "common_conflicts": ["成员不知道真实目标", "理想包装犯罪", "上层牺牲下层维持隐蔽"]},
        ],
        "institution_checklist": [
            "谁拥有名义最高权力？",
            "谁拥有实际最高权力？",
            "谁能任命与罢免人？",
            "谁能收税、征兵、审判、赦免、封赏？",
            "哪个职位最体面但没实权？",
            "哪个职位最不起眼但掌握命脉？",
        ],
    },
    "economy_templates": {
        "resource_economy_profile_template": {
            "id": "",
            "name": "",
            "scope_ref": {"type": "", "id": ""},
            "one_sentence_summary": "",
            "resource_model": {"key_resources": []},
            "currency_model": {"currency_type": "", "units": {"small": "", "medium": "", "large": ""}},
            "time_model": {"calendar_name": "", "era_system": "", "plot_deadlines": []},
            "technology_model": {"tech_level_summary": "", "core_technologies": []},
            "production_and_trade": {"production_model": {}, "trade_model": {}},
            "bottlenecks": [],
            "class_effects": {},
            "crisis_triggers": [],
            "story_interfaces": {
                "conflict": "",
                "character_choice": "",
                "cost": "",
                "reveal": "",
                "usable_scenes": [],
            },
        },
        "economy_scenarios": [
            {"id": "agrarian_empire", "name": "农耕帝国套", "core": "粮食、土地、户籍与税赋构成权力核心。"},
            {"id": "theocratic_holy_city", "name": "神权圣城套", "core": "信仰、圣物、朝圣与赎罪决定财富和秩序。"},
            {"id": "cultivation_sect", "name": "修真宗门套", "core": "灵气、灵石、丹药、洞府和传承决定阶层。"},
            {"id": "maritime_city_state", "name": "海贸城邦套", "core": "航线、港口、保险、信用票据和海上武力决定命脉。"},
            {"id": "steppe_tribal", "name": "草原部族套", "core": "牲畜、水草、铁器、婚姻和战利品构成财富。"},
            {"id": "wasteland_base", "name": "废土基地套", "core": "水、食物、药品、燃料与配给制度决定生死。"},
            {"id": "cyber_corporate_city", "name": "赛博公司城套", "core": "数据、身份、算力、居住许可与医疗技术取代土地。"},
            {"id": "space_colony", "name": "星际殖民地套", "core": "氧气、水、能源、质量配额和轨道窗口决定秩序。"},
        ],
        "economy_checklist": [
            "这个世界最稀缺的资源是什么？",
            "谁生产、运输、垄断、消费它？",
            "货币背后真正兑换的是什么？",
            "时间制度如何制造期限？",
            "技术掌握在谁手里？",
            "黑市卖什么、伪造什么、偷什么？",
        ],
    },
    "extension_templates": {
        "daily_life_profile": {
            "id": "",
            "name": "",
            "scope_ref": {"type": "", "id": ""},
            "one_sentence_texture": "",
            "food": {},
            "clothing": {},
            "housing": {},
            "hygiene_and_medicine": {},
            "etiquette": {},
            "family_and_life_cycle": {},
            "leisure": {},
            "class_variation": {},
            "narrative_hooks": [],
        },
        "belief_mythos_profile": {
            "id": "",
            "name": "",
            "scope_ref": {"type": "", "id": ""},
            "cosmology": {},
            "afterlife": {},
            "sacred_values": {},
            "rituals": {},
            "sacred_objects_and_places": {},
            "institutions": {},
            "heresies_and_dissent": {},
            "myth_vs_truth": {},
            "narrative_hooks": [],
        },
        "information_profile": {
            "id": "",
            "name": "",
            "scope_ref": {"type": "", "id": ""},
            "communication_channels": [],
            "archives": {},
            "censorship_and_propaganda": {},
            "rumor_ecology": {},
            "literacy_and_education": {},
            "maps_and_geography_knowledge": {},
            "secret_communication": {},
            "knowledge_gaps": {},
            "narrative_hooks": [],
        },
        "ecology_profile": {
            "id": "",
            "name": "",
            "scope_ref": {"type": "", "id": ""},
            "biome": {},
            "species": {},
            "disasters": [],
            "diseases_and_contamination": {},
            "domestication_and_hunting": {},
            "environmental_history": {},
            "narrative_hooks": [],
        },
        "aesthetic_profile": {
            "id": "",
            "name": "",
            "scope_ref": {"type": "", "id": ""},
            "tone_keywords": [],
            "visual_palette": {},
            "sensory_palette": {},
            "recurring_images": [],
            "recurring_objects": [],
            "language_style": {},
            "anti_style": {},
            "emotional_arc": {},
            "narrative_hooks": [],
        },
        "secret_entry": {
            "id": "",
            "name": "",
            "category": "",
            "public_belief": "",
            "partial_truth": "",
            "hidden_truth": "",
            "deeper_truth": "",
            "why_secret_exists": {},
            "knowers": {},
            "clues": {},
            "reveal_ladder": [],
            "protection_mechanisms": {},
            "narrative_payoff": {},
        },
        "value_conflict": {
            "id": "",
            "issue": "",
            "side_a": {},
            "side_b": {},
            "side_c_optional": {},
            "stakes": {},
            "pressure_on_protagonist": {},
            "scenes": {},
            "thematic_function": {},
        },
        "story_interface": {
            "id": "",
            "world_element_ref": {"type": "", "id": ""},
            "element_summary": "",
            "narrative_functions": {},
            "character_pressure": {},
            "cost_structure": {},
            "reveal_structure": {},
            "scene_seeds": [],
            "arc_usage": {},
        },
        "module_checklist": [
            "它限制了谁？",
            "它诱惑了谁？",
            "它保护了谁？",
            "它伤害了谁？",
            "它能不能制造至少一个具体场景？",
            "它能不能在后文被重新解释？",
        ],
    },
    "title_lexicon_pack": _TITLE_LEXICON_PACK,
    "value_conflict_prompts": _VALUE_CONFLICT_PROMPTS,
}


def default_minimum_world_system() -> dict[str, Any]:
    return copy.deepcopy(_DEFAULT_MINIMUM_WORLD_SYSTEM)


def default_minimum_extension_pack() -> dict[str, Any]:
    return copy.deepcopy(_DEFAULT_MINIMUM_EXTENSION_PACK)


def default_world_extensions() -> dict[str, Any]:
    return copy.deepcopy(_DEFAULT_WORLD_EXTENSIONS)


def default_template_libraries() -> dict[str, Any]:
    return copy.deepcopy(_TEMPLATE_LIBRARIES)


def empty_world_root() -> dict[str, Any]:
    return {
        "minimum_world_system": default_minimum_world_system(),
        "minimum_extension_pack": default_minimum_extension_pack(),
        "world_bible": {},
        "map_atlas": {},
        "story_engine": {},
        "institution_profiles": [],
        "resource_economy_profiles": [],
        "world_extensions": default_world_extensions(),
        "template_libraries": default_template_libraries(),
    }
